### ISSUE TITLE
Reset of home won't stick

### ISSUE THREAD

**Issue by stevempotter** [moschotto/OpenTX_GPS_Telemetry#34]
When I reset telemetry, I see the home location momentarily go to zero km, but instantly goes back to the default bad home position that is 6316 km away from here. Why are my actual home coords being overwritten by bogus ones? My GPS has a good fix with 9 sats, and the correct aircraft position is showing at the bottom. But home always says
57,762289, -122.908029 which seems to be in BC, Canada. (I am in Ireland)

**Comment by moschotto** [comment]
hi - it's probably because your **pilot** latitude and **pilot** longitude is just set once **by opentx/edgetx**. 
in the current code, pilot-lat and pilot-lon is used to set the home position. i did not dig into the opentx/edgetx code, but i guess in case the radio itself has an internal GPS, the coordinates of the internal GPS will be used to set the pilot-lat and pilot-lon. 

see:
https://doc.open-tx.org/opentx-2-3-lua-reference-guide/part_iii_-_opentx_lua_api_reference/general-functions-less-than-greater-than-luadoc-begin-general/getvalue#return-value

anyway, i changed the T16 code to use the actual drone position as home position instead of the pilot-lat pilot-lon AFTER resetting the STATISTICS

can you try this one and let me know if it works for you 

[main.lua.txt](https://github.com/moschotto/OpenTX_GPS_Telemetry/files/11094370/main.lua.txt)
(rename the file to main.lua and copy it to the radio)

**Comment by stevempotter** [comment]
Yes, that seems to work. Thank you!!

**Comment by moschotto** [comment]
So you used the new script, right? And please let me know your radio and fw version.

**Comment by stevempotter** [comment]
Yes, I used the new script you sent. Here are 2 photos of my firmwares. I am using the Radiomaster TX16S.
https://photos.app.goo.gl/FG1SGNzs6Wyg5g59A

**Comment by moschotto** [comment]
Thanks for the info. Does it have an internal GPS which is enabled?

**Comment by stevempotter** [comment]
No internal GPS.  I didn't even know about this option -- Thanks! 
Where can I learn more about which GPS modules would work in Radiomaster Tx16s? Which UART connector on the radio does it use?

**Comment by moschotto** [comment]
I don’t own a T16s but

https://youtu.be/euqpChlyouE

**Comment by stevempotter** [comment]
Hi @moschotto, I have now installed an internal GPS in my TX16S. I can see it has a fix, sats, and HDOP in the Statistics debug window of EdgeTX. Now, how to get my radio's GPS coordinates to display in a widget? I don't see any VALUE that corresponds to internal GPS in the widget settings. It would be great if your Lua script were to keep showing updated HOME GPS coordinates if I am moving. I would not easily be able to reset stats while flying.

**Comment by moschotto** [comment]
Hi - I am not planning to re-implement this feature because the widget is not meant to be a „MOVING plane/quad finder tool“ (the radio moves). Please try release 2.4 because this still uses the PILOT lat/lon for setting the home position. In version 2.4 version the home will be constantly updated but I can’t say if the pilot lat/lon will be updated as well. please keep in mind that I have no influence how the pilot lat/lon will be updated - It’s done automatically by edgetx

https://github.com/moschotto/OpenTX_GPS_Telemetry/releases

> I don't see any VALUE that corresponds to internal GPS in the widget settings. 

I can’t test and verify this because I am using a x9 lite radio. Furthermore the internal GPS is not supported by the edgetx simulator and therefore…….

I can’t find any useful usecase for an internal GPS module. Of course there are other requests that wants this functionality (plane finder with an arrow) but honestly,- i want use google maps to locate and find the crashed plane / quad. And this is the idea of the widget

**Comment by stevempotter** [comment]
"to locate and find the crashed plane / quad. And this is the idea of the widget"

That's great. I was imagining walking toward the lost model and noting whether the radio's HOME GPS coords are getting closer. But, yes, I can use my phone and Google Maps if I have a mobile coverage in the place where I am flying. Sometimes I don't.
