### ISSUE TITLE
Feature request: automatically set home point upon first arm?

### ISSUE THREAD

**Issue by bede** [moschotto/OpenTX_GPS_Telemetry#36]
Hi there,
This is a really useful script that solves a problem for me, thank you! I wondered if it might be 1) useful 2) possible to automatically set the home location for the first time upon arming? After this it should require manual reset of course.

Thanks!

**Comment by moschotto** [comment]
Hi - from my point of view it doesn’t make sense to set home on arming (a switch) because in case of a crash you might rearm several times (turtle mode etc)… 

„set home point once“ (initial arm) is basically implemented when you set it manually. The idea is, that you „kind of verify“ the GPS fix by looking at the coordinates and satellites…

**Comment by bede** [comment]
Thanks for your reply. This is why I suggested only resetting for the first arm, I.e. when a home point has not already been set.

Agree that requiring manual verification is very sensible. I may fork your script to include e.g. altitude to facilitate flying in the event of video loss.

Thanks again for a really useful project, feel free to close.

**Comment by moschotto** [comment]
Ok. 

Note: Altitude is already included - see screenshots

**Comment by bede** [comment]
Yes, but not at the same time as home distance – for flying blind both are
valuable at the same time

**Comment by moschotto** [comment]
Every logging line has ALT included and therefore you should have it… type the coordinates in your phone and get the ALT from the logviewer
